### Create Study Plan
POST http://localhost:8080/api/v1/study-plan
Authorization: Basic user bd5f51f3-f75b-46ab-8d20-4a8fca1b7a20
Content-Type: application/json

{
  "year": 2026,
  "month": 9,
  "slotsPerDay" : 3
}
